language: java
sudo: false
dist: xenial

# Using -q Quiet output which only show errors, to overcome TravisCI log limit issue
script: mvn clean install -q -B -V | grep -v DEBUG; exit "${PIPESTATUS[0]}";

cache:
  directories:
  - $HOME/.m2_1
  - $HOME/.m2
  - features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher-new/node_modules
  - features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store-new/node_modules
